const Occupation = require("../model/Occupation");
const Tables = require("../model/Tables");
const Accounts = require("../model/Accounts");
const mongoose = require("mongoose")

// Show all tables
async function getAllOccupations(req, res) {
  try {
    const occupations = await Occupation.find()

    if (occupations.length == 0) return res.status(404).json({ error: "There are no records in the database" })

    res.status(200).json(occupations)

  } catch (error) {
    console.log(error);
    res.status(500).json({ error: "Server error" + error })
  }
}

// Return occuptions by ID
async function getOccupionByID(req, res) {
  try {

    // TO DO
    

  } catch (error) {
    res.status(500).json({ error: "Server error" + error })
  }
}

// Return array of all occuptions at the current date and time.
async function getCurrentOccupions(req, res) {
  try {
    
    // TO DO
    

  } catch (error) {
    res.status(500).json({ error: "Server error" + error })
  }
}

// Create a new record
async function addOccupation(req, res) {
  console.log("trying to add a occupation..")
  try {

    // Checking for required fields
    if (!req.body.tableID || !req.body.waiterID) {
      return res.status(400).json({ error: "Missing required fields." });
    }

    // Checking if the IDs are valid
    if (!mongoose.Types.ObjectId.isValid(req.body.tableID)) {
      return res.status(404).json({ error: 'tableID - Not a valid ID format.' });
    }

    if (!mongoose.Types.ObjectId.isValid(req.body.waiterID)) {
      return res.status(404).json({ error: 'waiterID - Not a valid ID format.' });
    }

    // Check if ID exists
    const account = await Accounts.findById(req.body.waiterID);
    const table = await Tables.findById(req.body.tableID);

    if (!account) return res.status(404).json({ error: 'This account does not exist' });
    if (account.role != "waiter") return res.status(404).json({ error: 'This account is not of a waiter' });

    if (!table) return res.status(404).json({ error: 'Table does not exist' });

    // Create a new object
    let newOccupation = {
      tableID: req.body.tableID,
      waiterID: req.body.waiterID,
      checkOutTime: null
    };
    // All other fields are autogenerated

    // Find if it exsists is in the DB already
    const occupation = await Occupation.find(newOccupation)

    // If it EXISTS in the DB
    if (occupation.length > 0) return res.status(409).json({ error: "The record is already in the database" })

    // If not create
    Occupation.insertMany(new Occupation(newOccupation))  // add to the db
    res.status(201).json(occupation) // return as a JSON object + HTTP-status code 201 (created).   

  } catch (error) {
    res.status(500).json({ error: "Server error" + error })
  }
}


// Update a record
async function updateOccupation(req, res) {
  try {

    const occupation = await Occupation
      .findByIdAndUpdate(
        req.params.id,
        {
          tableID: req.body.tableID,
          waiterID: req.body.waiterID,
          startTime: req.body.startTime,
          totalPrice: req.body.totalPrice,
          checkOutTime: req.body.checkOutTime
        },
        { new: true });

    // If not found - when var is null -> !var == true
    if (!occupation) return res.status(404).json({ error: 'ID not found' });

    res.status(200).json(occupation)
  } catch (error) {
    res.status(500).json({ error: "Server error" + error })
  }
}

// Delete a record
async function deleteOccupation(req, res) {
  try {
    const occupation = await Occupation.findByIdAndRemove(req.params.id);

    if (!occupation) return res.status(404).json({ error: 'ID not found' });

    res.status(200).json(occupation);
  } catch (error) {
    res.status(500).json({ error: "Server error" + error })
  }
}




/*
async function verifyIDs(tableID, waiterID) {
  if (!mongoose.Types.ObjectId.isValid(tableID)) {
    throw new Error('TableID - Not a valid ID format.');
  }

  if (!mongoose.Types.ObjectId.isValid(waiterID)) {
    throw new Error('WaiterID - Not a valid ID format.');
  }

  // Check if ID exists
  const account = await Accounts.findById(waiterID);
  const table = await Tables.findById(tableID);

  if (!account) throw new Error('This account does not exist');
  if (account.role != "waiter") throw new Error('This account is not of a waiter');

  if (!table) throw new Error('Table does not exist');
}*/

module.exports = { getAllOccupations, addOccupation, updateOccupation, deleteOccupation, getCurrentOccupions, getOccupionByID };